### PR TITLE
adds tests

### PR DESCRIPTION
**Pull request by kartaris**
catch2 with Conan instead of gtest used in #22 

- adds basic test as an example
- adds test step into CI/CD pipeline
- adds test section into README.md

### CODE REVIEW

**Comment by kartaris** [comment]
in progress

**Comment by kartaris** [comment]
> in progress

Done @bolknote

**Comment by deadem** [comment]
> > in progress
> 
> Done @bolknote

А где тесты?

https://github.com/bolknote/gopnik2/pull/23/checks

Run ctest --extra-verbose
UpdateCTestConfiguration  from :/home/runner/work/gopnik2/gopnik2/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/runner/work/gopnik2/gopnik2/DartConfiguration.tcl
Test project /home/runner/work/gopnik2/gopnik2
Constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
**No tests were found!!!**

**Comment by kartaris** [comment]
> > > in progress
> > 
> > 
> > Done @bolknote
> 
> А где тесты?
> 
> https://github.com/bolknote/gopnik2/pull/23/checks
> 
> Run ctest --extra-verbose UpdateCTestConfiguration from :/home/runner/work/gopnik2/gopnik2/DartConfiguration.tcl UpdateCTestConfiguration from :/home/runner/work/gopnik2/gopnik2/DartConfiguration.tcl Test project /home/runner/work/gopnik2/gopnik2 Constructing a list of tests Updating test list for fixtures Added 0 tests to meet fixture requirements Checking test dependency graph... Checking test dependency graph end **No tests were found!!!**

едут #24

**Pull request merged**
